name: PlayerTags
authors: [wildmaster84]
api-version: 1.13
description: Tags plugin
main: me.wild.PlayerTags
version: '1.0'
depend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.
folia-supported: true

commands:
  tags:
    description: tags command
    usage: /tags | /tags reload